//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edicion
    {
        public int ID { get; set; }
        public string Tecnico { get; set; }
        public string Medico { get; set; }
        public string CadenaInicial { get; set; }
        public string CadenaFinal { get; set; }
    }
}
