//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informe
    {
        public int id { get; set; }
        public string CuerpoRealizaEnc { get; set; }
        public string CuerpoValidaEnc { get; set; }
        public System.DateTime fechainforme { get; set; }
        public System.DateTime fecharevision { get; set; }
        public int paciente { get; set; }
        public string medicoinforma { get; set; }
        public string medicorevisa { get; set; }
    }
}
